//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHU
    {
        public int MaSP { get; set; }
        public int MaLoai { get; set; }
        public Nullable<System.DateTime> Thang { get; set; }
        public Nullable<decimal> DoanhThu1 { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
