//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MaHD { get; set; }
        public string TenNV { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string NoiDung { get; set; }
        public Nullable<float> ChietKhau { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
