//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONGNV
    {
        public string MaNV { get; set; }
        public string HoTenNV { get; set; }
        public string TinhChatCV { get; set; }
        public string CaLam { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
