//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYEN
    {
        public string MaNV { get; set; }
        public string TenTK { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> MaQuyen { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual QUYEN QUYEN { get; set; }
    }
}
